#!/usr/bin/env bash
# A script that loops to 10 and prints different phrases for each iteration
#+ "bad luck" for the fourth iteration
#+ "good luck" for the 8th iteration
#+ "Best School" for the the other iterations

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done